pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  environment {
        PATH = "/Users/satishgovindwar/jenkins-docker-bin:/usr/local/bin:/usr/bin:/bin"
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}

